### ISSUE TITLE
Make `filename` visible in `TestFile`?

### ISSUE THREAD

**Issue by mgree** [justinj/datadriven#6]
It would be convenient for debugging to have `filename` be `pub` and not `Option`al in `TestFile`. It seems like `filename` is always set to `Some` anyway, and having the filename around will make it easier to debug failures (e.g., attach the current filename to a logging span).

Would you be open to a PR for this?

**Comment by justinj** [comment]
Yup sounds good to me! I forget why it was optional in the first place (probably: I was still new to Rust at the time).

**Comment by justinj** [comment]
Fixed in #7.
